import { StyleSheet } from 'react-native';

export const styleSheet = (windowHeight, windowWidth) => {
    const wp = windowWidth / 360 
    const hp = windowHeight / 640

    return StyleSheet.create({
        "qrscan": {
            "opacity": 1,
            "position": "relative",
            "backgroundColor": "rgba(0, 0, 0, 0.7019607843137254)",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": windowWidth,
            "height": windowHeight,
            "left": 0,
            "top": 0
        },
        "qrscan_x145": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 249.07 * wp,
            "height": 333.12 * hp,
            "left": 55,
            "top": 127.88
        },
        "qrscan_x145_x8": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 46,
            "borderTopRightRadius": 46,
            "borderBottomLeftRadius": 46,
            "borderBottomRightRadius": 46,
            "width": 249.07,
            "height": 245,
            "left": 0,
            "top": 0
        },
        "qrscan_x145_x144": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 240,
            "height": 51.31,
            "left": 4.53,
            "top": 281.8
        },
        "qrscan_x145_x144_x146": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 240,
            "height": 51.31,
            "left": 0,
            "top": 0
        },
        "qrscan_x145_x144_x146_qr0d071759": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(255, 255, 255, 1)",
            "fontSize": 23,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 240,
            "height": 28,
            "left": 0,
            "top": 0
        },
        "qrscan_x145_x144_x146_qr": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(188, 188, 188, 1)",
            "fontSize": 14,
            "fontWeight": "300",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 186,
            "height": 17,
            "left": 27,
            "top": 34.31
        },
        "qrscan_x34": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 84,
            "height": 84,
            "left": 138,
            "top": 525
        },
        "qrscan_x34_x26": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 84,
            "height": 84,
            "left": 0,
            "top": 0
        },
        "qrscan_x34_x27": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 62,
            "height": 62,
            "left": 11,
            "top": 11
        },
        "qrscan_iconCloseWhite": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 27,
            "height": 27,
            "left": 19,
            "top": 37
        },
        "qrscan_iconCloseWhite_x4781838cancelclosedeleteexitlogouticon": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 14,
            "borderTopRightRadius": 14,
            "borderBottomLeftRadius": 14,
            "borderBottomRightRadius": 14,
            "width": 27,
            "height": 27,
            "left": 0,
            "top": 0
        },
        "qrscan_iconCamerachange": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 37,
            "height": 37,
            "left": 273,
            "top": 549
        },
        "qrscan_iconCamerachange_sync": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 37,
            "height": 37,
            "left": 0,
            "top": 0
        }
    })
}