import { StyleSheet } from 'react-native';

export const styleSheet = (windowHeight, windowWidth) => {
    const wp = windowWidth / 360
    const hp = windowHeight / 640
    return StyleSheet.create({
        "qrcode": {
            "opacity": 1,
            "position": "relative",
            "backgroundColor": "rgba(0, 135, 141, 1)",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": windowWidth,
            "height": windowHeight,
            "left": 0,
            "top": 0
        },
        "qr_body": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 230 * wp,
            "height": 48 * hp,
            "left": 65 * wp,
            "top": 478 * hp,
        },
        "qr_header": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(255, 255, 255, 1)",
            "fontSize": 22 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 230 * wp,
            "height": 27 * hp,
            "left": 0,
            "top": 0,
            'textAlign': "center"
        },
        "qr_answer": {
            "opacity": 0.5,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(255, 255, 255, 1)",
            "fontSize": 14 * hp,
            "fontWeight": "300",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 186 * wp,
            "height": 17 * hp,
            "left": 19 * wp,
            "top": 31 * hp
        },
        "qrcode_x41": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 1)",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 360 * wp,
            "height": 100 * hp,
            "left": 0,
            "top": 540 * hp
        },
        "qrcode_x56": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 48 * wp,
            "height": 75 * hp,
            "left": 71.05 * wp,
            "top": 545 * hp
        },
        "qrcode_x56_x180a11c0": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(29, 29, 29, 1)",
            "fontSize": 14 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 48 * wp,
            "height": 17 * hp,
            "left": 0,
            "top": 50 * hp
        },
        "qrcode_x56_iconHand": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 46.91 * wp,
            "height": 47 * hp,
            "left": 1,
            "top": 0
        },
        "qrcode_x56_iconHand_hand": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 46.91 * wp,
            "height": 47 * hp,
            "left": 0,
            "top": 0,
            'resizeMode': 'contain'
        },
        "qrcode_x55": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 48 * wp,
            "height": 75 * hp,
            "left": 240.95 * wp,
            "top": 545 * hp
        },
        "qrcode_x55_xafc4ab4c": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(29, 29, 29, 1)",
            "fontSize": 14 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 48 * wp,
            "height": 17 * hp,
            "left": 0,
            "top": 50 * hp
        },
        "qrcode_x55_iconDocuments": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 47 * wp,
            "height": 47 * hp,
            "left": 1 * wp,
            "top": 0
        },
        "qrcode_x55_iconDocuments_documents": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 47 * wp,
            "height": 47 * hp,
            "left": 0,
            "top": 0,
            "resizeMode": 'contain'
        },
        "qrcode_x232ca2d889": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 1.5 * wp,
            "height": 68 * hp,
            "left": 179.67 * wp,
            "top": 553.5 * hp
        },
        "qrcode_x22192304d2": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 187.65,
            "height": 187.36 * hp,
            "left": 96.15,
            "top": 124.49 * hp
        },
        "qrcode_x22192304d2_x11e1bb77f3": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": -0.71,
            "top": 137.82 * hp
        },
        "qrcode_x22192304d2_x12842451c5": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": -0.71,
            "top": 66.43 * hp
        },
        "qrcode_x22192304d2_x13cda063cf": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 167.75,
            "top": 66.43 * hp
        },
        "qrcode_x22192304d2_x146fefc0aa": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 186.65,
            "top": 137.82
        },
        "qrcode_x22192304d2_x150eaeee68": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 167.75,
            "top": 137.82
        },
        "qrcode_x22192304d2_x16262d3f09": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 5.55,
            "top": 137.82
        },
        "qrcode_x22192304d2_x17c6ad4561": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 5.55,
            "top": 66.43 * hp
        },
        "qrcode_x22192304d2_x1898199f64": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 161.49,
            "top": 66.43 * hp
        },
        "qrcode_x22192304d2_x190f0940f1": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 161.49,
            "top": 137.82 * hp
        },
        "qrcode_x22192304d2_x4": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 3.49,
            "height": 0,
            "left": 164.98,
            "top": 138.59 * hp
        },
        "qrcode_x22192304d2_x5": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 3.49,
            "height": 0,
            "left": 164.98,
            "top": 67.72 * hp
        },
        "qrcode_x22192304d2_x6": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2.32,
            "height": 0,
            "left": 0,
            "top": 138.59 * hp
        },
        "qrcode_x22192304d2_x7": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2.32,
            "height": 0,
            "left": 0,
            "top": 67.72 * hp
        },
        "qrcode_x22192304d2_x8": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 4.65,
            "height": 0 * hp,
            "left": 2.32,
            "top": 138.59 * hp
        },
        "qrcode_x22192304d2_x9": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 4.65,
            "height": 0,
            "left": 2.32,
            "top": 67.72 * hp
        },
        "qrcode_x22192304d2_x10": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2.32,
            "height": 0,
            "left": 162.66,
            "top": 67.72 * hp
        },
        "qrcode_x22192304d2_x11": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2.32,
            "height": 0,
            "left": 162.66,
            "top": 138.59 * hp
        },
        "qrcode_x22192304d2_x20": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 47.83,
            "top": 17.89 * hp
        },
        "qrcode_x22192304d2_x21": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 47.83,
            "top": -1 * hp
        },
        "qrcode_x22192304d2_x22": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 119.22,
            "top": -1 * hp
        },
        "qrcode_x22192304d2_x23": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 119.22,
            "top": 17.89 * hp
        },
        "qrcode_x22192304d2_x24": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 119.22,
            "top": 186.36 * hp
        },
        "qrcode_x22192304d2_x25bc564de4": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2 * hp,
            "left": 47.83,
            "top": 186.36 * hp
        },
        "qrcode_x22192304d2_x26": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 119.22,
            "top": 180.09
        },
        "qrcode_x22192304d2_x27": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 47.83,
            "top": 180.09
        },
        "qrcode_x22192304d2_x28": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 119.22,
            "top": 24.15
        },
        "qrcode_x22192304d2_x29": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 2,
            "height": 2,
            "left": 47.83,
            "top": 24.15
        },
        "qrcode_x22192304d2_x1261b4cbc9": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13,
            "left": 48.83,
            "top": 18.89
        },
        "qrcode_x22192304d2_x13": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 120.22,
            "top": 18.89 * hp
        },
        "qrcode_x22192304d2_x14": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 120.22,
            "top": 184.23 * hp
        },
        "qrcode_x22192304d2_x15": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 48.83,
            "top": 184.23 * hp
        },
        "qrcode_x22192304d2_x16": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 120.22 * wp,
            "top": 181.09 * hp
        },
        "qrcode_x22192304d2_x17": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 48.83 * wp,
            "top": 181.09 * hp
        },
        "qrcode_x22192304d2_x18": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 48.83 * wp,
            "top": 22.02 * hp
        },
        "qrcode_x22192304d2_x19": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 0,
            "height": 3.13 * hp,
            "left": 120.22,
            "top": 22.02 * hp
        },
        "qrcode_x109": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 230.83 * wp,
            "height": 379.92 * hp,
            "left": 64.59 * wp,
            "top": 72.54 * hp
        },
        "qrcode_x109_x25": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 1)",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "borderTopLeftRadius": 20,
            "borderTopRightRadius": 20,
            "borderBottomLeftRadius": 20,
            "borderBottomRightRadius": 20,
            "shadowColor": "rgb(0,  0,  0)",
            "shadowOpacity": 0.41568627450980394,
            "shadowOffset": {
                "width": 5 * wp,
                "height": 5 * hp
            },
            "shadowRadius": 6,
            "width": 230.83 * wp,
            "height": 379.92 * hp,
            "left": 0,
            "top": 0
        },
        "qrcode_x109_x107": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 173 * wp,
            "height": 173 * hp,
            "left": 29.41 * wp,
            "top": 42.46 * hp
        },
        "qrcode_x109_x107_x104": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 165.57 * wp,
            "height": 165.57 * hp,
            "left": 4 * wp,
            "top": 4 * hp
        },
        "qrcode_x109_x107_x104_rwyyrzli98hnwpoQrCodeTransparentPng": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 165.57 * wp,
            "height": 165.57 * hp,
            "top": 0,
            alignItems: "center",
            justifyContent: 'center'
        },
        "qrcode_x109_x107_x105": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 173 * wp,
            "height": 173 * hp,
            "left": 0,
            "top": 0
        },
        "qrcode_x109_x107_x105_x106": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 173 * wp,
            "height": 173 * hp,
            "left": 0,
            "top": 0
        },
        "qrcode_x109_x107_x105_x106_x35": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 58.63 * wp,
            "height": 58.63 * hp,
            "left": 115.37 * wp,
            "top": -1 * hp
        },
        "qrcode_x109_x107_x105_x106_x110": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 56.63 * wp,
            "height": 56.63 * hp,
            "left": 116.37 * wp,
            "top": 116.37 * hp
        },
        "qrcode_x109_x107_x105_x106_x110_x36": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 58.63 * wp,
            "height": 58.63 * hp,
            "left": -1 * wp,
            "top": -1 * hp
        },
        "qrcode_x109_x107_x105_x106_x37": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 58.63 * wp,
            "height": 58.63 * hp,
            "left": -1 * wp,
            "top": -1 * hp
        },
        "qrcode_x109_x107_x105_x106_x38": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 58.63 * wp,
            "height": 58.63 * hp,
            "left": -1 * wp,
            "top": 115.37 * hp
        },
        "qrcode_x8c7d203a": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(29, 29, 29, 1)",
            "fontSize": 24 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 62 * wp,
            "height": 29 * hp,
            "left": 149 * wp,
            "top": 381.73 * hp
        },
        "qrcode_x": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(188, 188, 188, 1)",
            "fontSize": 16 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 132 * wp,
            "height": 19 * hp,
            "left": 114 * wp,
            "top": 421.34 * hp
        },
        "qrcode_x1": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "width": 42.7 * wp,
            "height": 55 * hp,
            "left": 159.39 * wp,
            "top": 325.44 * hp
        },
        "qrcode_x1_userprofil": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 44.95,
            "height": 44.95 * hp,
            "left": -1.5,
            "top": -0.75 * hp
        },
        "qrcode_x1_userprofil_user": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 44.95,
            "height": 44.95 * hp,
            "left": 0,
            "top": 0
        },
        "qrcode_x1_x12": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 42.7,
            "height": 42.7 * hp,
            "left": 0,
            "top": 0
        },
        "qrcode_x154": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 34.12,
            "height": 48.34 * hp,
            "left": 15,
            "top": 19.66 * hp
        },
        "qrcode_x154_x48": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": 30.12 * wp,
            "height": 29.88 * hp,
            "left": 2.5 * wp,
            "top": -0.5 * hp,
            "resizeMode": 'contain'
        },
        "qrcode_x154_xf6337869": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(255, 255, 255, 1)",
            "fontSize": 10 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 34 * wp,
            "height": 12 * hp,
            "left": 0,
            "top": 36.34 * hp
        },
        "qrcode_x151": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "transparent",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 33.44 * wp,
            "height": 49.63 * hp,
            "left": 311.28 * wp,
            "top": 18.37 * hp
        },
        "qrcode_x151_scan": {
            "opacity": 1,
            "position": "absolute",
            "backgroundColor": "rgba(255, 255, 255, 0)",
            "color": "rgba(255, 255, 255, 1)",
            "fontSize": 10 * hp,
            "fontWeight": "700",
            "fontStyle": "normal",
            "fontFamily": "Apple SD Gothic Neo",
            "textAlign": "center",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "paddingTop": 0,
            "paddingRight": 0,
            "paddingBottom": 0,
            "paddingLeft": 0,
            "width": 25 * wp,
            "height": 12 * hp,
            "left": 4.72 * wp,
            "bottom": 0
        },
        "qrcode_x151_x49": {
            "opacity": 1,
            "position": "absolute",
            "marginTop": 0,
            "marginRight": 0,
            "marginBottom": 0,
            "marginLeft": 0,
            "borderTopLeftRadius": 0,
            "borderTopRightRadius": 0,
            "borderBottomLeftRadius": 0,
            "borderBottomRightRadius": 0,
            "width": "auto",
            "height": 32.47 * wp,
            "left": -0.5 * hp,
            "top": -0.5 * wp,
            "right": 1.5 * hp
        }
    });
}
